# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# Synchronize panes
bind-key y set-window-option synchronize-panes\; display-message "synchronize mode toggled."

# Lengthen the amount of time status messages are displayed
set-option -g display-time 3000
set-option -g display-panes-time 3000

# Set default prefix key to backtick
set-option -g prefix C-b

# Switch prefix key with F12 (backtick or Ctrl + b)
bind-key F11 set-option -g prefix C-b
bind-key F12 set-option -g prefix `

# Base index for windows and panes
set -g base-index 1
setw -g pane-base-index 1

# Mouse and status options
# Uncomment the following lines for graphical environment
set -g mouse on
set-option -g mouse-select-pane on
set-option -g status-keys vi
set-option -g bell-action any
set-option -g set-titles on
set-option -g set-titles-string '#H:#S.#I.#P #W #T'
set-option -g visual-bell off

# Window options
setw -g mode-keys vi
setw -g monitor-activity on
setw -g automatic-rename off

# Status line configuration
set-option -g status-justify left
set-option -g status-bg green
set-option -g status-fg white
set-option -g status-left '#[fg=brightwhite,bold]#S #[fg=brightred,bold]| #[default]'
set-option -g status-interval 5
set-option -g status-right '#[fg=brightred,bold] | #[fg=darkblue,bold]%H:%M #[fg=darkblue,bold]%d-%b-%Y#[default]'
set-option -g status-left-length 40
set-option -g status-right-length 80
set -g history-limit 10000

# Highlight active window
setw -g window-status-style bg=green,fg=brightwhite,bold
setw -g window-status-current-style bg=white,fg=darkblack,bold

# Additional window status styles
setw -g window-status-bell-style fg=red,bold
#setw -g window-status-content-style fg=yellow,bold
setw -g window-status-activity-style fg=yellow,bold
#setw -g window-status-bell-attr default
#setw -g window-status-bell-fg red
#setw -g window-status-content-attr default
#setw -g window-status-content-fg yellow
#setw -g window-status-activity-attr default
#setw -g window-status-activity-fg yellow

# Pane border colors
set-option -g pane-border-style fg=white,bg=black
set-option -g pane-active-border-style fg=green,bg=black
set-option -g message-style fg=black,bg=green

# Easy clear history
bind-key L clear-history


#==Window==
# Shift + arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window


# Easily reorder windows with CTRL+SHIFT+Arrow
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1



#==Pane==
# Set easier window split keys
bind-key v split-window -v
bind-key h split-window -h


# Use Alt + arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D


#==Valid color names==
#==Basic Colors==
#black
#red
#green
#yellow
#blue
#magenta
#cyan
#white

#==Bright Colors==
#brightblack
#brightred
#brightgreen
#brightyellow
#brightblue
#brightmagenta
#brightcyan
#brightwhite

#==Dark Colors==
#darkblack
#darkred
#darkgreen
#darkyellow
#darkblue
#darkmagenta
#darkcyan
#darkwhite